name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23lis9B40jCcLXo2gZ"
GITHUB_OWNER = "zoharluo"
GITHUB_REPO = "navsphere-data"
GITHUB_BRANCH = "main"
